services:
  web:
    env:
      DJANGO_SETTINGS_MODULE: "mysite.settings"
    command: gunicorn mysite.wsgi:application 

hooks:
  build:
    - python manage.py collectstatic --noinput
    - python manage.py runserver 0.0.0.0:8081
